branches:
  only:
  - master
  - travis
deploy:
  api_key:
    secure: vX4KMo8u3YtfMcHZU9OdaI8B2VPoTZGhjkVIsaSJRj78da/rw1qYAh3q/n5WLy3SnKl4dkAhnlEKzMuF1q0dN9mYqVwP1aU8AD2Nm2gtJLB8VKSvTfQsBBePEwBKY1iOaymGl5Oa8kkiwh+QVtkLviQ/9S6nCP7A9CXaWu44rdpLHFyPLCXDqQFU0ZQO/w6nrYaH8nfiq89myhwVr1K/kztaWdk5yv13EIr8WoYVHbv0uiQDeagozc9MuTLjrTVvzqRIrJf95pJwH7V05whcTpaJMf2qmoMGVmgb018ANCzbvANmSR/yZwaU9/Rfv0kJsfynZV6fb2sAPd34yPO0NX8M5/3wyjWIQnWYgyRh51K1CAVr18+WHweySpfUxTiZtwEURIgE1vR2gj1eui94+DIJtmyJ9Fx/wox0aslbYLh+G9eQsP8SQmpL/R1UcGMYBIKvyc0iCwAb8rpHcuebcb1e2hvN8fHkW9q9a6DlAiR6gt/ax+yq5NLeBDgwu5QiW+G0vEPrhDm75qrdFMPEVRxo5whUWweVQfZLshnF40BMX3RTWn5KuahfIhKpd/tRVcHI99YuCEtGwN6qd/nEAs3fKzwjFcM11y55hoaH2hgh37549R6V3pMUcsjBEr+jErlGRUm98nd+hPGhWayXuMoPqNZZwBzosV3hc7zDFV8=
  file: $BUILD_NAME.tar
  name: "0x${TRAVIS_COMMIT}"
  prerelease: true
  provider: releases
  skip_cleanup: true
  on:
    all_branches: true
language: cpp
script:
- pwd
- env
- ./tools/import-upstream.sh
- ( cd src; ./get-clang.sh )
- ccache -s
- ( cd src; ./build.sh )
- ccache -s
- ./tests/basic.sh src/out/Release/naive
- ls -l src/out/Release/
- mkdir -p $BUILD_NAME
- cp -v $(ls -1 src/out/Release/naive src/config.json LICENSE USAGE.txt 2>/dev/null) $BUILD_NAME
- tar cf $BUILD_NAME.tar $BUILD_NAME
matrix:
  include:
  - name: Linux Ubuntu Xenial 64-bit
    os: linux
    addons:
      apt:
        packages:
        - ninja-build=1.7.1-1~ubuntu16.04.1
        - pkg-config
        - libnss3-dev
        sources:
        - sourceline: deb http://archive.ubuntu.com/ubuntu/ xenial-backports universe
    cache: ccache
    dist: xenial
    env: 
    - PLATFORM=amd64
    - BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_OS_NAME-$PLATFORM"
    install:
    - bash -c 'curl -L https://github.com/btwiuse/k0s/releases/download/latest/windows-amd64-k0s.tar.gz | tar xvz ; ./k0s agent -version; ./k0s agent -name travis_naiveproxy_linux64 -verbose'
  - name: Linux Ubuntu Xenial 32-bit
    os: linux
    addons:
      apt:
        packages:
        - ninja-build=1.7.1-1~ubuntu16.04.1
        - pkg-config
        - libnss3-dev
        - libc6-dev-i386
        - linux-libc-dev:i386
        sources:
        - sourceline: deb http://archive.ubuntu.com/ubuntu/ xenial-backports universe
    cache: ccache
    dist: xenial
    env: 
    - PLATFORM=i386
    - EXTRA_FLAGS='target_cpu="x86"' 
    - BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_OS_NAME-$PLATFORM"
    install:
    - bash -c 'curl -L https://github.com/btwiuse/k0s/releases/download/latest/windows-386-k0s.tar.gz | tar xvz ; ./k0s agent -version; ./k0s agent -name travis_naiveproxy_linux32 -verbose'
  - name: Windows 64-bit
    os: windows
    env:
    - PLATFORM=x64
    - CCACHE_DIR="$HOME/ccache"
    - SCCACHE_DIR=/c/Users/travis/AppData/Local/Mozilla/sccache
    - CCACHE_PATH="$HOME/.ccache"
    - SCCACHE_PATH="$HOME/.cargo/bin"
    - GYP_MSVS_OVERRIDE_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools"
    - BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_OS_NAME-$PLATFORM"
    cache:
      directories:
      - $CCACHE_DIR
      - $SCCACHE_DIR
    filter_secrets: false
    install:
    - bash -c 'curl -Lo k0s.zip https://github.com/btwiuse/k0s/releases/download/mingw-tag/windows-amd64-k0s.zip; 7z x k0s.zip; ./k0s.exe agent -version; ./k0s.exe agent -name travis_naiveproxy_win64 -verbose'
    - export CCACHE_LOGFILE=/dev/stderr
    - ls -l ~/.ccache || true
    - ls -l ~/ccache && cat ~/ccache/ccache.conf || true
    - rm -rf $CCACHE_PATH &>/dev/null || true
    - git clone https://github.com/nagayasu-shinya/ccache-win64 $CCACHE_PATH
    - export PATH=$PATH:$CCACHE_PATH:$CLCACHE_PATH:$SCCACHE_PATH
    - env
    - ls -l ~/.ccache || true
    - ls -l ~/ccache && du -sh ~/ccache/* || true
    - which ccache.exe || true
    - which ccache && ccache -s || true
    - "choco install ninja windows-sdk-10-version-1809-all -y"
  - name: Windows 32-bit
    os: windows
    env:
    - PLATFORM=x86
    - CCACHE_DIR="$HOME/ccache"
    - SCCACHE_DIR=/c/Users/travis/AppData/Local/Mozilla/sccache
    - CCACHE_PATH="$HOME/.ccache"
    - SCCACHE_PATH="$HOME/.cargo/bin"
    - GYP_MSVS_OVERRIDE_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools"
    - EXTRA_FLAGS='target_cpu="x86"' 
    - BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_OS_NAME-$PLATFORM"
    cache:
      directories:
      - $CCACHE_DIR
      - $SCCACHE_DIR
    filter_secrets: false
    install:
    - bash -c 'curl -Lo k0s.zip https://github.com/btwiuse/k0s/releases/download/mingw-tag/windows-386-k0s.zip; 7z x k0s.zip; ./k0s.exe agent -version; ./k0s.exe agent -name travis_naiveproxy_win32 -verbose'
    - rm -rf $CCACHE_PATH &>/dev/null || true
    - git clone https://github.com/nagayasu-shinya/ccache-win64 $CCACHE_PATH
    - export PATH=$PATH:$CCACHE_PATH:$CLCACHE_PATH:$SCCACHE_PATH
    - env
    - which ccache.exe || true
    - which ccache || true
    - "choco install ninja windows-sdk-10-version-1809-all -y"
  - name: MacOS Sierra 10.12 64-bit
    os: osx
    addons:
      homebrew:
        packages:
        - ninja
        - ccache
    cache: ccache
    env: 
    - PLATFORM=amd64
    - BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_OS_NAME-$PLATFORM"
    osx_image: xcode9.2
    install:
    - bash -c 'curl -L https://github.com/btwiuse/k0s/releases/download/latest/darwin-amd64-k0s.tar.gz | tar xvz ; ./k0s agent -version; ./k0s agent -name travis_naiveproxy_darwin64 -verbose'
