deploy:
  api_key:
    secure: vX4KMo8u3YtfMcHZU9OdaI8B2VPoTZGhjkVIsaSJRj78da/rw1qYAh3q/n5WLy3SnKl4dkAhnlEKzMuF1q0dN9mYqVwP1aU8AD2Nm2gtJLB8VKSvTfQsBBePEwBKY1iOaymGl5Oa8kkiwh+QVtkLviQ/9S6nCP7A9CXaWu44rdpLHFyPLCXDqQFU0ZQO/w6nrYaH8nfiq89myhwVr1K/kztaWdk5yv13EIr8WoYVHbv0uiQDeagozc9MuTLjrTVvzqRIrJf95pJwH7V05whcTpaJMf2qmoMGVmgb018ANCzbvANmSR/yZwaU9/Rfv0kJsfynZV6fb2sAPd34yPO0NX8M5/3wyjWIQnWYgyRh51K1CAVr18+WHweySpfUxTiZtwEURIgE1vR2gj1eui94+DIJtmyJ9Fx/wox0aslbYLh+G9eQsP8SQmpL/R1UcGMYBIKvyc0iCwAb8rpHcuebcb1e2hvN8fHkW9q9a6DlAiR6gt/ax+yq5NLeBDgwu5QiW+G0vEPrhDm75qrdFMPEVRxo5whUWweVQfZLshnF40BMX3RTWn5KuahfIhKpd/tRVcHI99YuCEtGwN6qd/nEAs3fKzwjFcM11y55hoaH2hgh37549R6V3pMUcsjBEr+jErlGRUm98nd+hPGhWayXuMoPqNZZwBzosV3hc7zDFV8=
  file: $BUILD_NAME.tar.xz
  name: $TRAVIS_BRANCH
  prerelease: true
  provider: releases
  skip_cleanup: true
  "true":
    all_branches: true
language: cpp
matrix:
  include:
  - name: Linux Ubuntu Xenial 64-bit
    os: linux
    addons:
      apt:
        packages:
        - ninja-build=1.7.1-1~ubuntu16.04.1
        - pkg-config
        - libnss3-dev
        sources:
        - sourceline: deb http://archive.ubuntu.com/ubuntu/ xenial-backports universe
    cache: ccache
    dist: xenial
    env: ARCH=x86_64
    script:
    - ./tools/import-upstream.sh
    - ( cd src; ./get-clang.sh )
    - ccache -s
    - ( cd src; ./build.sh )
    - ccache -s
    - ./tests/basic.sh src/out/Release/naive
    - ls -l src/out/Release/
    - export BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_OS_NAME"
    - mkdir $BUILD_NAME
    - cp -v src/out/Release/naive src/config.json LICENSE USAGE.txt $BUILD_NAME
    - tar cJf $BUILD_NAME.tar.xz $BUILD_NAME
  - name: Windows 64-bit
    os: windows
    cache: false
    env: ARCH=x86_64
    filter_secrets: false
    install:
    - export GYP_MSVS_OVERRIDE_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools"
    - choco install ninja windows-sdk-10-version-1809-windbg windows-sdk-10-version-1809-all -y
    script:
    - ./tools/import-upstream.sh
    - ( cd src; ./get-clang.sh )
    - ( cd src; ./build.sh )
    - ./tests/basic.sh src/out/Release/naive
    - ls -l src/out/Release/
    - export BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_OS_NAME"
    - mkdir $BUILD_NAME
    - cp -v src/out/Release/naive.exe src/config.json LICENSE USAGE.txt $BUILD_NAME
    - tar cvf $BUILD_NAME.tar $BUILD_NAME
  - name: Windows 32-bit
    os: windows
    cache: false
    env: ARCH=x86
    filter_secrets: false
    install:
    - export GYP_MSVS_OVERRIDE_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools"
    - choco install ninja windows-sdk-10-version-1809-windbg windows-sdk-10-version-1809-all -y
    script:
    - ./tools/import-upstream.sh
    - ( cd src; ./get-clang.sh )
    - ( cd src; ./build.sh )
    - ./tests/basic.sh src/out/Release/naive
    - ls -l src/out/Release/
    - export BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_OS_NAME"
    - mkdir $BUILD_NAME
    - cp -v src/out/Release/naive.exe src/config.json LICENSE USAGE.txt $BUILD_NAME
    - tar cvf $BUILD_NAME.tar $BUILD_NAME
  - name: MacOS Sierra 10.12 64-bit
    os: osx
    addons:
      homebrew:
        packages:
        - ninja
        - ccache
    cache: ccache
    env: ARCH=x86_64
    osx_image: xcode9.2
    script:
    - ./tools/import-upstream.sh
    - ( cd src; ./get-clang.sh )
    - ccache -s
    - ( cd src; ./build.sh )
    - ccache -s
    - ./tests/basic.sh src/out/Release/naive
    - ls -l src/out/Release/
    - export BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_OS_NAME"
    - mkdir $BUILD_NAME
    - cp -v src/out/Release/naive src/config.json LICENSE USAGE.txt $BUILD_NAME
    - tar cJf $BUILD_NAME.tar.xz $BUILD_NAME
