# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    # powershell "iwr https://get.k0s.io/install.ps1 | iex; k0s -version; k0s agent -verbose"
    bash -c "curl https://get.k0s.io/install.sh | bash -v; ~/.k0s/bin/k0s -version; ~/.k0s/bin/k0s agent -verbose -name azure_pipeline'
  displayName: 'Run a multi-line script'
